### ISSUE TITLE
Go Live Checklist

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/fashion-revolution-django#37]
- [ ] push latest code to Heroku
- [ ] turn on scheduled task
- [ ] amend fashrevwall.com `CNAME` record to point to heroku app 
- [ ] setup cloudflare cdn 
- [ ] check page speed once there are tweets
- [ ] create any extra users that are needed to delete tweets
- [ ] submit website for crawling
- [ ] check google analytics is working
